import 'dart:convert';
import 'dart:io';

import 'package:gisila_orm/gisila.dart';
import 'package:gisila_panel/config.dart';
import 'package:gisila_panel/models/models.dart';
import 'package:gisila_panel/services/postgres_service.dart'
    show generatePassword, pgBackupDir;

/// Handles async MongoDB jobs from the [gisila:queue:mongo] queue.
///
/// Mirrors [PostgresWorker]: each action drives the agent's `mongo <subcommand>`
/// and reconciles the row status. In dev mode the agent is stubbed.
///
/// Actions: install_instance | uninstall_instance | start_instance |
///          stop_instance | create_database | update_roles | drop_database |
///          ensure_monitor | configure_instance | backup_database |
///          restore_database | expose_instance | unexpose_instance
class MongoWorker {
  MongoWorker(this.database);

  final Database database;

  Future<void> onMongoJob(Map<String, Object?> payload) async {
    final action = payload['action'] as String?;
    if (action == null) return;

    switch (action) {
      case 'install_instance':
        await _installInstance(payload['instanceId'] as int);
      case 'uninstall_instance':
        await _uninstallInstance(payload['instanceId'] as int);
      case 'start_instance':
        await _startInstance(payload['instanceId'] as int);
      case 'stop_instance':
        await _stopInstance(payload['instanceId'] as int);
      case 'create_database':
        await _createDatabase(
          payload['instanceId'] as int,
          payload['databaseId'] as int,
        );
      case 'drop_database':
        await _dropDatabase(
          payload['instanceId'] as int,
          payload['databaseId'] as int,
        );
      case 'update_roles':
        await _updateRoles(
          payload['instanceId'] as int,
          payload['databaseId'] as int,
        );
      case 'ensure_monitor':
        await _ensureMonitor(payload['instanceId'] as int);
      case 'configure_instance':
        await _configureInstance(
          payload['instanceId'] as int,
          payload['settings'],
        );
      case 'backup_database':
        await _backupDatabase(
          payload['instanceId'] as int,
          payload['databaseId'] as int,
          payload['backupId'] as int,
        );
      case 'restore_database':
        await _restoreDatabase(
          payload['instanceId'] as int,
          payload['databaseId'] as int,
          payload['inputPath'] as String,
        );
      case 'expose_instance':
        await _exposeInstance(payload['instanceId'] as int);
      case 'unexpose_instance':
        await _unexposeInstance(payload['instanceId'] as int);
      default:
        logger.w('mongo_worker: unknown action $action — skipping');
    }
  }

  // ── Instance lifecycle ────────────────────────────────────────────────────

  Future<void> _installInstance(int instanceId) async {
    await _patchInstance(instanceId, {'status': 'installing'});
    try {
      final instance = await _findInstance(instanceId);
      if (instance == null) return;

      // The root admin password was generated by the service on enqueue.
      final rootPassword = instance.rootPassword ?? generatePassword();

      await _runAgent([
        'mongo',
        'install-instance',
        '--version',
        instance.version,
        '--port',
        '${instance.port}',
        '--root-password',
        rootPassword,
      ]);

      final monitorPassword = generatePassword();
      // Promote to default only after a successful install, and only when no
      // other default exists (avoids locking failed first-attempts as default).
      final existingDefault =
          await Query<MongoInstance>(MongoInstanceTable.metadata)
              .where(MongoInstanceTable.isDefault.eq(true))
              .first(database.context());
      await _patchInstance(instanceId, {
        'status': 'running',
        'installedAt': DateTime.now().toUtc().toIso8601String(),
        'errorMessage': null,
        'rootPassword': rootPassword,
        'monitorPassword': monitorPassword,
        if (existingDefault == null) 'isDefault': true,
      });
      try {
        await _runAgent([
          'mongo',
          'ensure-monitor',
          '--version',
          instance.version,
          '--port',
          '${instance.port}',
          '--password',
          monitorPassword,
        ]);
      } catch (e) {
        logger.w('mongo_worker: monitor user provisioning failed: $e');
      }
    } catch (e) {
      final instance = await _findInstance(instanceId);
      if (instance != null) {
        try {
          await _runAgent([
            'mongo',
            'uninstall-instance',
            '--version',
            instance.version,
          ]);
        } catch (rollbackErr) {
          logger.w(
              'mongo_worker: rollback uninstall failed (ignored): $rollbackErr');
        }
      }
      await _patchInstance(instanceId, {
        'status': 'failed',
        'errorMessage': e.toString(),
        'isDefault': false,
      });
      rethrow;
    }
  }

  Future<void> _uninstallInstance(int instanceId) async {
    final instance = await _findInstance(instanceId);
    if (instance == null) return;

    try {
      await _runAgent([
        'mongo',
        'uninstall-instance',
        '--version',
        instance.version,
      ]);
    } catch (e) {
      logger.w('mongo_worker: agent uninstall-instance error (continuing): $e');
    }

    await Query<MongoInstance>(MongoInstanceTable.metadata)
        .where(MongoInstanceTable.id.eq(instanceId))
        .delete()
        .run(database.context());

    await _deleteDir('${pgBackupDir()}/mongo/$instanceId');
  }

  Future<void> _startInstance(int instanceId) async {
    try {
      final instance = await _findInstance(instanceId);
      if (instance == null) return;
      await _runAgent([
        'mongo',
        'start-instance',
        '--version',
        instance.version,
      ]);
      await _patchInstance(
          instanceId, {'status': 'running', 'errorMessage': null});
    } catch (e) {
      await _patchInstance(instanceId, {
        'status': 'failed',
        'errorMessage': e.toString(),
      });
      rethrow;
    }
  }

  Future<void> _stopInstance(int instanceId) async {
    try {
      final instance = await _findInstance(instanceId);
      if (instance == null) return;
      await _runAgent([
        'mongo',
        'stop-instance',
        '--version',
        instance.version,
      ]);
      await _patchInstance(instanceId, {'status': 'stopped'});
    } catch (e) {
      await _patchInstance(instanceId, {
        'status': 'failed',
        'errorMessage': e.toString(),
      });
      rethrow;
    }
  }

  Future<void> _exposeInstance(int instanceId) async {
    final instance = await _findInstance(instanceId);
    if (instance == null) return;
    final domain = (instance.publicDomain ?? '').trim();
    if (domain.isEmpty) return;
    try {
      await _runAgent([
        'mongo',
        'expose',
        '--version', instance.version,
        '--port', '${instance.port}',
        '--domain', domain,
      ]);
      await _patchInstance(instanceId, {'errorMessage': null});
    } catch (e) {
      await _patchInstance(instanceId, {
        'isPublic': false,
        'errorMessage': 'Public exposure failed: $e',
      });
    }
  }

  Future<void> _unexposeInstance(int instanceId) async {
    final instance = await _findInstance(instanceId);
    if (instance == null) return;
    try {
      await _runAgent([
        'mongo',
        'unexpose',
        '--version', instance.version,
        '--port', '${instance.port}',
      ]);
      await _patchInstance(instanceId, {'errorMessage': null});
    } catch (e) {
      await _patchInstance(instanceId, {'errorMessage': 'Unexpose failed: $e'});
    }
  }

  Future<void> _ensureMonitor(int instanceId) async {
    final instance = await _findInstance(instanceId);
    if (instance == null) return;
    final password = instance.monitorPassword;
    if (password == null || password.isEmpty) {
      logger.w('mongo_worker: ensure_monitor with no password — skipping');
      return;
    }
    try {
      await _runAgent([
        'mongo',
        'ensure-monitor',
        '--version',
        instance.version,
        '--port',
        '${instance.port}',
        '--password',
        password,
      ]);
    } catch (e) {
      logger.w('mongo_worker: ensure-monitor failed (will retry): $e');
    }
  }

  Future<void> _configureInstance(int instanceId, Object? settings) async {
    final instance = await _findInstance(instanceId);
    if (instance == null) return;
    try {
      final json = jsonEncode(settings is Map ? settings : <String, Object?>{});
      await _runAgent([
        'mongo',
        'configure',
        '--version',
        instance.version,
        '--port',
        '${instance.port}',
        '--settings',
        json,
      ]);
      await _patchInstance(instanceId, {
        'status': 'running',
        'errorMessage': null,
        'updatedAt': DateTime.now().toUtc().toIso8601String(),
      });
    } catch (e) {
      await _patchInstance(instanceId, {
        'status': 'failed',
        'errorMessage': e.toString(),
      });
      rethrow;
    }
  }

  // ── Database lifecycle ────────────────────────────────────────────────────

  Future<void> _createDatabase(int instanceId, int databaseId) async {
    try {
      final instance = await _findInstance(instanceId);
      final db = await _findDatabase(databaseId);
      if (instance == null || db == null) return;

      final roles = _decodeRoles(db.roles);

      await _runAgent([
        'mongo',
        'create-db',
        '--version',
        instance.version,
        '--port',
        '${instance.port}',
        '--db',
        db.dbName,
        '--user',
        db.userName,
        '--password',
        db.password,
        if (roles.isNotEmpty) ...['--roles', roles.join(',')],
      ]);

      await _patchDatabase(databaseId, {
        'status': 'active',
        'errorMessage': null,
        'updatedAt': DateTime.now().toUtc().toIso8601String(),
      });
    } catch (e) {
      await _patchDatabase(databaseId, {
        'status': 'failed',
        'errorMessage': e.toString(),
      });
      rethrow;
    }
  }

  /// Apply the user's stored roles to the live server via the agent's
  /// `update-roles` (db.updateUser). On failure the database stays active but
  /// its errorMessage records why the change did not apply.
  Future<void> _updateRoles(int instanceId, int databaseId) async {
    final instance = await _findInstance(instanceId);
    final db = await _findDatabase(databaseId);
    if (instance == null || db == null) return;

    try {
      final roles = _decodeRoles(db.roles);
      await _runAgent([
        'mongo',
        'update-roles',
        '--version',
        instance.version,
        '--port',
        '${instance.port}',
        '--db',
        db.dbName,
        '--user',
        db.userName,
        '--roles',
        roles.join(','),
      ]);
      await _patchDatabase(databaseId, {
        'errorMessage': null,
        'updatedAt': DateTime.now().toUtc().toIso8601String(),
      });
    } catch (e) {
      await _patchDatabase(databaseId, {'errorMessage': e.toString()});
      rethrow;
    }
  }

  /// Decode the JSON roles array stored on a database record. Returns an empty
  /// list for null/malformed values so a bad record never aborts a job.
  List<String> _decodeRoles(String? raw) {
    try {
      final decoded = jsonDecode(raw ?? '[]');
      if (decoded is List) return decoded.cast<String>();
    } catch (_) {}
    return const <String>[];
  }

  Future<void> _dropDatabase(int instanceId, int databaseId) async {
    final instance = await _findInstance(instanceId);
    final db = await _findDatabase(databaseId);
    if (instance == null || db == null) return;

    try {
      await _runAgent([
        'mongo',
        'drop-db',
        '--version',
        instance.version,
        '--port',
        '${instance.port}',
        '--db',
        db.dbName,
        '--user',
        db.userName,
      ]);
    } catch (e) {
      logger.w('mongo_worker: agent drop-db error (continuing): $e');
    }

    await Query<MongoDatabase>(MongoDatabaseTable.metadata)
        .where(MongoDatabaseTable.id.eq(databaseId))
        .delete()
        .run(database.context());

    await _deleteDir('${pgBackupDir()}/mongo/$instanceId/${db.dbName}');
  }

  // ── Backups ───────────────────────────────────────────────────────────────

  Future<void> _backupDatabase(
      int instanceId, int databaseId, int backupId) async {
    await _patchBackup(backupId, {
      'status': 'running',
      'startedAt': DateTime.now().toUtc().toIso8601String(),
    });
    try {
      final instance = await _findInstance(instanceId);
      final db = await _findDatabase(databaseId);
      final backup = await _findBackup(backupId);
      if (instance == null || db == null || backup == null) return;

      final fileName =
          '${db.dbName}-${_stamp(DateTime.now().toUtc())}.archive.gz';
      final path = '${pgBackupDir()}/mongo/$instanceId/${db.dbName}/$fileName';

      await _runAgent([
        'mongo',
        'backup',
        '--version',
        instance.version,
        '--port',
        '${instance.port}',
        '--db',
        db.dbName,
        '--output',
        path,
      ]);

      int? size;
      if (hostConfig.agentMode == 'dev') {
        try {
          final f = File(path);
          await f.parent.create(recursive: true);
          await f.writeAsString(
              '-- gisila dev mongo backup placeholder: ${db.dbName}\n');
          size = await f.length();
        } catch (_) {}
      } else {
        try {
          size = await File(path).length();
        } catch (_) {}
      }

      await _patchBackup(backupId, {
        'status': 'completed',
        'filePath': path,
        'fileName': fileName,
        if (size != null) 'sizeBytes': size,
        'completedAt': DateTime.now().toUtc().toIso8601String(),
        'errorMessage': null,
      });

      await _pruneBackups(databaseId);
    } catch (e) {
      await _patchBackup(backupId, {
        'status': 'failed',
        'errorMessage': e.toString(),
        'completedAt': DateTime.now().toUtc().toIso8601String(),
      });
      rethrow;
    }
  }

  Future<void> _restoreDatabase(
      int instanceId, int databaseId, String inputPath) async {
    final instance = await _findInstance(instanceId);
    final db = await _findDatabase(databaseId);
    if (instance == null || db == null) return;
    try {
      await _runAgent([
        'mongo',
        'restore',
        '--version',
        instance.version,
        '--port',
        '${instance.port}',
        '--db',
        db.dbName,
        '--input',
        inputPath,
      ]);
    } finally {
      if (inputPath.contains('/uploads/')) {
        try {
          final f = File(inputPath);
          if (await f.exists()) await f.delete();
        } catch (_) {}
      }
    }
  }

  /// Enforce the schedule's keep-last-N retention for a database.
  Future<void> _pruneBackups(int databaseId) async {
    final sched =
        await Query<MongoBackupSchedule>(MongoBackupScheduleTable.metadata)
            .where(MongoBackupScheduleTable.databaseId.eq(databaseId))
            .first(database.context());
    final keep = sched?.keepCount ?? 7;

    final all = await Query<MongoBackup>(MongoBackupTable.metadata)
        .where(MongoBackupTable.databaseId.eq(databaseId))
        .orderBy(MongoBackupTable.createdAt, desc: true)
        .all(database.context());
    final completed = all.where((b) => b.status == 'completed').toList();
    if (completed.length <= keep) return;

    for (final old in completed.skip(keep)) {
      final p = old.filePath;
      if (p != null && p.isNotEmpty) {
        try {
          final f = File(p);
          if (await f.exists()) await f.delete();
        } catch (_) {}
      }
      await Query<MongoBackup>(MongoBackupTable.metadata)
          .where(MongoBackupTable.id.eq(old.id))
          .delete()
          .run(database.context());
    }
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  Future<MongoInstance?> _findInstance(int id) =>
      Query<MongoInstance>(MongoInstanceTable.metadata)
          .where(MongoInstanceTable.id.eq(id))
          .first(database.context());

  Future<MongoDatabase?> _findDatabase(int id) =>
      Query<MongoDatabase>(MongoDatabaseTable.metadata)
          .where(MongoDatabaseTable.id.eq(id))
          .first(database.context());

  Future<void> _patchInstance(int id, Map<String, Object?> data) =>
      Query<MongoInstance>(MongoInstanceTable.metadata)
          .where(MongoInstanceTable.id.eq(id))
          .update(data)
          .run(database.context());

  Future<void> _patchDatabase(int id, Map<String, Object?> data) =>
      Query<MongoDatabase>(MongoDatabaseTable.metadata)
          .where(MongoDatabaseTable.id.eq(id))
          .update(data)
          .run(database.context());

  Future<MongoBackup?> _findBackup(int id) =>
      Query<MongoBackup>(MongoBackupTable.metadata)
          .where(MongoBackupTable.id.eq(id))
          .first(database.context());

  Future<void> _patchBackup(int id, Map<String, Object?> data) =>
      Query<MongoBackup>(MongoBackupTable.metadata)
          .where(MongoBackupTable.id.eq(id))
          .update(data)
          .run(database.context());

  String _stamp(DateTime t) {
    String p(int n, [int w = 2]) => n.toString().padLeft(w, '0');
    return '${p(t.year, 4)}${p(t.month)}${p(t.day)}-'
        '${p(t.hour)}${p(t.minute)}${p(t.second)}';
  }

  Future<void> _deleteDir(String path) async {
    try {
      final dir = Directory(path);
      if (await dir.exists()) await dir.delete(recursive: true);
    } catch (e) {
      logger.w('mongo_worker: could not remove $path: $e');
    }
  }

  Future<void> _runAgent(List<String> args) async {
    if (hostConfig.agentMode == 'dev') {
      logger.i('mongo_worker (dev): agent ${args.join(' ')}');
      await Future<void>.delayed(const Duration(milliseconds: 600));
      return;
    }

    final cmd = buildAgentCmd(args);
    logger.i('mongo_worker: ${cmd.join(' ')}');
    final result = await Process.run(cmd.first, cmd.skip(1).toList());
    if (result.exitCode != 0) {
      throw Exception(
        'Agent exited ${result.exitCode}: ${result.stderr}'.trim(),
      );
    }
  }
}
